### PR TITLE
Treat null importer as noOp if url is not a file: url

### LINKED ISSUE #82: Imports shall not be resolved relative to working directory of dart-sass-embedded process
`compileString` should not resolve imports relative to working directory of compiler process.

This issue can be reproduced with both node host and ruby host.

Correct behavior of throwing `[Error]: Can't find stylesheet to import` on `sass`:

``` js
const fs = require('fs')
const sass = require('sass')
fs.writeFileSync('child.scss', 'a{b:c}');
console.log(sass.compileString('@import "child.scss";').css)
```

Reproduction with node host:

``` js
const fs = require('fs')
const sass = require('sass-embedded')
fs.writeFileSync('child.scss', 'a{b:c}');
console.log(sass.compileString('@import "child.scss";').css)
```

Reproduction with ruby host (fixed in 1.3.0, need version before <1.3 to reproduce):

``` ruby
require 'sass-embedded'
File.write('child.scss', 'a{b:c}')
puts Sass.compile_string('@import "child.scss";').css
```

Since ruby host has the capability of launching embedded compiler process and keep re-using it, here is another experiment involving changing working directory on host after embedded compiler has been launched:

``` ruby
require 'sass-embedded'
File.write('child.scss', 'a{b:c}')
Sass.info # launch dart-sass-embedded in the same working directory as host
Dir.chdir '/tmp' do # change working directory of host
  # import can still be resolved relative to compiler's working directory
  puts Sass.compile_string('@import "child.scss";').css
end
```

### PR DESCRIPTION
**Pull request by ntkme**
This PR fixes https://github.com/sass/dart-sass-embedded/issues/82.

See https://github.com/sass/sass-spec/pull/1785
See sass/embedded-host-node#128

### CODE REVIEW

**Comment by nex3** [comment]
I think the desirable behavior here, to match the JS API spec as updated in https://github.com/sass/sass/pull/3278, is to set a `NoOpImporter` *only if `url` isn't a `file:` URL*, and to use a filesystem importer otherwise.

**Comment by ntkme** [comment]
>  A relative load's URL is first resolved relative to [[url]], then resolved to a file on disk if it's a `file://` URL. If it can't be resolved to a file on disk, it's then passed to [[importers]] and [[loadPaths]].

I think the language I picked matches the current behavior: the js-api (non-embedded) only checks if `url` is null or not to set it to NoOpImporter or FileSystemImporter. This change and https://github.com/sass/embedded-host-node/pull/124 together makes the embedded host consistent with non-embedded js-api.

Today (non-embedded js-api):

- If url is null -> NoOpImporter
- If url is non-null -> FileSystemImporter

If I understand your proposal correctly:

- If url is null -> NoOpImporter
- If url is non-file url -> NoOpImporter
- If url is file url -> FileSystemImporter

@nex3 Is that what you mean? In that case we also need to update the non-embedded js-api.

**Comment by ntkme** [comment]
Either way I think it is simpler to just treat null as NoOp here in dart-sass-embedded, and have host checking for url/importer and pass the correct kind of importer to the embedded compiler.

**Review by nex3 — APPROVED** [review]

**Comment by nex3** [comment]
@ntkme Looks like this is breaking some legacy importer tests, can you take a look?

**Comment by ntkme** [comment]
@nex3 Looks like we need https://github.com/sass/embedded-host-node/pull/128. The legacy can resolve from working directory without filename set (meaning no file: url). In other words, it always needs a FileSystemImporter.

**Pull request merged**
