### PR TITLE
Implement support for sourceMapIncludeSources

### PR DESCRIPTION
**Pull request by stof**
This needs https://github.com/sass/embedded-protocol/pull/87 to be merged first for the protocol. This PR implements this option in dart-sass-embedded.

### CODE REVIEW

**Comment by jathak** [comment]
This should be unblocked now. Sorry for the delay!

**Comment by ntkme** [comment]
Still have to wait for `dart-sass` to cut a release, so that the `pubspec` can be updated to catch up the necessary changes.

**Comment by stof** [comment]
@ntkme not needed. This relies on the dart API of dart-sass, not the JS API.

**Comment by nex3** [comment]
Is there a test for this in `sass-spec`? If not, we should add one.

**Comment by jathak** [comment]
I believe https://github.com/sass/sass-spec/pull/1757 added one but skipped it for embedded. Should we make a PR to enable it?

**Comment by nex3** [comment]
Yeah, although I just realized this PR is for the embedded compiler not the host so not quite yet. This should add a Dart test, though.

**Comment by stof** [comment]
The PR for the embedded-host is on my TODO list, but it requires merging the PRs for the protocol (now merged) and the compiler first. For now, I only created an issue there to track this: https://github.com/sass/embedded-host-node/issues/101

**Comment by stof** [comment]
@nex3 @jathak I added tests

**Comment by nex3** [comment]
The embedded host now supports linking PRs to the compiler, so you should be able to create it simultaneously with this CL.

**Comment by stof** [comment]
@nex3 I opened the PR (see the reference just above), but the linking did not work.

**Pull request merged**
