### PR TITLE
Add charset option

### PR DESCRIPTION
**Pull request by ntkme**
https://github.com/sass/sass/issues/3242

Depends on:
- https://github.com/sass/sass/pull/3346
- https://github.com/sass/dart-sass/pull/1732
- https://github.com/sass/embedded-protocol/pull/96

See https://github.com/sass/embedded-host-node/pull/152

### CODE REVIEW

**Comment by ntkme** [comment]
```
  Expected: '1.53.0'
    Actual: '1.54.0-dev'
     Which: is different.
            Expected: 1.53.0
              Actual: 1.54.0-dev
                         ^
             Differ at offset 3
```
@Goodwine Should I update the dart-sass dependency version to `1.54.0-dev`?

BTW, you can `git commit --allow-empty` to create empty commits that will trigger github events.

**Comment by Goodwine** [comment]
ah.. thanks for the tip 😅 

And yes, please update the version on both the dependency and the package itself, thanks!

**Comment by Goodwine** [comment]
discussing with @nex3 the failures on JS API Tests shouldn't be happening, I'll take a look here as well :)

**Comment by ntkme** [comment]
@Goodwine I found the CI had an incorrect clone path for dart-sass and was able to fix that. However JS API Tests now fails with some TS type checking:

```
node_modules/@types/tar/index.d.ts:252:36 - error TS2709: Cannot use namespace 'MiniPass' as a type.
252 export interface ReadEntry extends MiniPass, HeaderProperties {
                                   ~~~~~~~~
Found 1 error in node_modules/@types/tar/index.d.ts:252
```

@nex3 I thought this is already fixed in https://github.com/sass/embedded-host-node/commit/d6dbd87471c1e7bdf41660f27beb6b719679c075, any ideas why CI is failing?

**Comment by ntkme** [comment]
Ok turns out I did not rebase https://github.com/sass/embedded-host-node/pull/152 to the latest.

**Comment by ntkme** [comment]
@Goodwine Now CI fails with creating a symlink on windows only, for which I have no idea about. Otherwise, everything seems to be ok.

**Comment by ntkme** [comment]
Tried to replace `ln -s` with `cp -R` and it still fails on windows for some unknown reason, changed again to `mv` and now it seems to work.

**Review by Goodwine — APPROVED** [review]

**Comment by Goodwine** [comment]
Thanks for diving and fixing the errors, it's very interesting how it used to work but not anymore lol, but the changes look reasonable :)

**Pull request merged**
